version: '3.2'

services:

  change_bot:
    container_name: change_bot
    restart: always
    image: bomzheg/change_bot
    volumes:
      - type: "bind"
        source: "${HOME}/ChangeBot/log/"
        target: "/log"
      - type: "bind"
        source: "./config"
        target: "/config"
    env_file: config/.env
    entrypoint: [ "python3", "-m", "app"]
    networks:
      - reverse-proxy


networks:
  reverse-proxy:
    external:
      name: nginx-revers-proxy
