version: '3.2'

services:

  change_bot:
    container_name: change_bot
    restart: always
    image: bomzheg/change_bot
    volumes:
      - type: "bind"
        source: "./config"
        target: "/config"
    entrypoint: [ "python3", "-m", "app", "-p"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - reverse-proxy


networks:
  reverse-proxy:
    external:
      name: nginx-reverse-proxy
