bot:
  token: ""
  log_chat: -1001234567890
  superusers:
    - 666
rates:
  oer_token: ""
db:
  type: postgresql
  connector: asyncpg
  host: localhost
  port: 5432
  login: postgres
  password: postgres
  name: change_bot
